extends Node3D
## Valley scenery generated by tools/terrain (heightmap + painted splat maps).
## Rendering: shared flat grid chunks displaced on the GPU by valley_terrain.gdshader.
## Physics: one HeightMapShape3D. Heights are 1 m samples centred on the origin
## (sample i sits at x = i - (res - 1) / 2), matching the Blender preview mesh.

@export var data_dir := "res://terrains/valley/"
@export var material: ShaderMaterial = preload("res://materials/valley_terrain.tres")
@export var chunk_size := 64 # metres, one draw call each
@export var chunk_range := 320.0 # camera far is 250 m

var _heights := PackedFloat32Array()
var _res := 0
var _half := 0.0
var _splat: Array[Image] = []


func _ready() -> void:
	_ensure_data()
	_setup_material()
	_build_chunks()
	_build_collision()
	_build_walls()


# Lazy so Forest/Player/Mist can query heights regardless of _ready order.
func _ensure_data() -> void:
	if _res > 0:
		return
	var img: Image = load(data_dir + "height.res")
	_res = img.get_width()
	_half = (_res - 1) * 0.5
	_heights = img.get_data().to_float32_array()
	for i in 3:
		_splat.append(load(data_dir + "splat_%d.res" % i) as Image)


func get_height(x: float, z: float) -> float:
	_ensure_data()
	var fx := clampf(x + _half, 0.0, _res - 1.001)
	var fz := clampf(z + _half, 0.0, _res - 1.001)
	var ix := int(fx)
	var iz := int(fz)
	var tx := fx - ix
	var tz := fz - iz
	var i := iz * _res + ix
	var top := lerpf(_heights[i], _heights[i + 1], tx)
	var bottom := lerpf(_heights[i + _res], _heights[i + _res + 1], tx)
	return lerpf(top, bottom, tz)


## Layer weights at a point, nearest sample. Order: water_deep, water_shallow, rock,
## sand, scree, dirt, forest_floor, grass_dry, grass (see valley.json).
func get_layers(x: float, z: float) -> PackedFloat32Array:
	_ensure_data()
	var px := clampi(roundi(x + _half), 0, _res - 1)
	var pz := clampi(roundi(z + _half), 0, _res - 1)
	var out := PackedFloat32Array()
	for img in _splat:
		var c := img.get_pixel(px, pz)
		out.append_array([c.r, c.g, c.b])
	return out


func get_size() -> float:
	_ensure_data()
	return float(_res)


func _setup_material() -> void:
	material.set_shader_parameter("heightmap", ImageTexture.create_from_image(load(data_dir + "height.res")))
	for i in 3:
		material.set_shader_parameter("splat_%d" % i, ImageTexture.create_from_image(_splat[i]))
	material.set_shader_parameter("map_size", float(_res))


func _build_chunks() -> void:
	var mesh := PlaneMesh.new()
	mesh.size = Vector2(chunk_size, chunk_size)
	mesh.subdivide_width = chunk_size - 1 # 1 m quads
	mesh.subdivide_depth = chunk_size - 1
	# The plane is flat on the CPU; the shader lifts it, so culling needs the full height range.
	mesh.custom_aabb = AABB(Vector3(-chunk_size * 0.5 - 1.0, -20.0, -chunk_size * 0.5 - 1.0), Vector3(chunk_size + 2.0, 200.0, chunk_size + 2.0))
	var root := Node3D.new()
	root.name = "TerrainMesh"
	add_child(root)
	var n := ceili(float(_res) / chunk_size)
	for cz in n:
		for cx in n:
			var mi := MeshInstance3D.new()
			mi.name = "TerrainChunk_%d_%d" % [cx, cz]
			mi.mesh = mesh
			mi.material_override = material
			# Vertices land on sample positions: chunk edge at sample cx * chunk_size.
			mi.position = Vector3(cx * chunk_size + chunk_size * 0.5 - _half, 0.0, cz * chunk_size + chunk_size * 0.5 - _half)
			mi.visibility_range_end = chunk_range
			root.add_child(mi)


func _build_collision() -> void:
	var shape := HeightMapShape3D.new()
	shape.map_width = _res
	shape.map_depth = _res
	shape.map_data = _heights
	var body := StaticBody3D.new()
	body.name = "TerrainBody"
	# Layer 1 for player collision, layer 3 so the camera can test terrain only.
	body.collision_layer = 1 | (1 << 2)
	var cs := CollisionShape3D.new()
	cs.shape = shape
	body.add_child(cs)
	add_child(body)


func _build_walls() -> void:
	var half := _half + 0.5
	var t := 1.0
	var span := 2.0 * half + 2.0 * t
	var defs := [
		[Vector3(half + t * 0.5, 80, 0), Vector3(t, 300, span)],
		[Vector3(-half - t * 0.5, 80, 0), Vector3(t, 300, span)],
		[Vector3(0, 80, half + t * 0.5), Vector3(span, 300, t)],
		[Vector3(0, 80, -half - t * 0.5), Vector3(span, 300, t)],
	]
	var body := StaticBody3D.new()
	body.name = "Walls"
	body.collision_layer = 1
	for d in defs:
		var cs := CollisionShape3D.new()
		var box := BoxShape3D.new()
		box.size = d[1]
		cs.shape = box
		cs.position = d[0]
		body.add_child(cs)
	add_child(body)
